// Data makanan Hay Day — edit / tambah item di sini
const ITEMS = [
  {name:"Roti", level:2, category:"Toko Roti", img:"images/1.1.jpeg", price:10},
  {name:"Roti Jagung", level:7, category:"Toko Roti", img:"images/1.2.jpeg", price:35},
  {name:"Kue Kukis", level:10, category:"Toko Roti", img:"images/1.3.jpeg", price:35},
  {name:"Muffin Rasberi", level:19, category:"Toko Roti", img:"images/1.4.jpeg", price:35},
  {name:"Muffin Beri Hitam", level:26, category:"Toko Roti", img:"images/1.5.jpeg", price:35},
  {name:"Muffin Bluberi", level:33, category:"Toko Roti", img:"images/1.6.jpeg", price:35},
  {name:"Piza", level:33, category:"Toko Roti", img:"images/1.7.jpeg", price:35},
  {name:"Piza Pedas", level:37, category:"Toko Roti", img:"images/1.8.jpeg", price:35},
  {name:"Roti Kentang", level:39, category:"Toko Roti", img:"images/1.9.jpeg", price:35},
  {name:"Piza Frutti Di Mare", level:45, category:"Toko Roti", img:"images/1.10.jpeg", price:35},
  {name:"Kukis Jahe", level:86, category:"Toko Roti", img:"images/1.11.jpeg", price:35},
  {name:"Roti Pisang", level:91, category:"Toko Roti", img:"images/1.12.jpeg", price:35},
  {name:"Makarun", level:101, category:"Toko Roti", img:"images/1.13.jpeg", price:35},
  {name:"Snack Bar Kelapa Nanas", level:120, category:"Toko Roti", img:"images/1.14.jpeg", price:35},

  {name:"Krim", level:6, category:"Pengolahan Susu", img:"images/2.1.jpeg", price:20},
  {name:"Mentega", level:9, category:"Pengolahan Susu", img:"images/2.2.jpeg", price:20},
  {name:"Keju Sapi", level:12, category:"Pengolahan Susu", img:"images/2.3.jpeg", price:20},
  {name:"Keju Kambing", level:33, category:"Pengolahan Susu", img:"images/2.4.jpeg", price:30},
  
  {name:"Gula Cokelat", level:7, category:"Pabrik Gula", img:"images/3.1.jpeg", price:20},
  {name:"Gula Putih", level:13, category:"Pabrik Gula", img:"images/3.2.jpeg", price:20},
  {name:"Sirup", level:18, category:"Pabrik Gula", img:"images/3.3.jpeg", price:20},

  {name:"Berondong Jagung", level:8, category:"Panci Berondong", img:"images/4.1.jpeg", price:35},
  {name:"Berondong Mentega", level:16, category:"Panci Berondong", img:"images/4.2.jpeg", price:35},
  {name:"Berondong Pedas", level:25, category:"Panci Berondong", img:"images/4.3.jpeg", price:35},
  {name:"Berondong Madu", level:40, category:"Panci Berondong", img:"images/4.4.jpeg", price:35},
  {name:"Berondong Cokelat", level:44, category:"Panci Berondong", img:"images/4.5.jpeg", price:35},
  {name:"Kudapan Campur", level:64, category:"Panci Berondong", img:"images/4.6.jpeg", price:35},

  {name:"Panekuk", level:9, category:"Panggangan BBQ", img:"images/5.1.jpeg", price:35},
  {name:"Daging & Telur", level:11, category:"Panggangan BBQ", img:"images/5.2.jpeg", price:35},
  {name:"Hamburger", level:18, category:"Panggangan BBQ", img:"images/5.3.jpeg", price:35},
  {name:"Sate Domba Muda", level:25, category:"Panggangan BBQ", img:"images/5.4.jpeg", price:35},
  {name:"Burger Ikan", level:27, category:"Panggangan BBQ", img:"images/5.5.jpeg", price:35},
  {name:"Tomat Panggang", level:30, category:"Panggangan BBQ", img:"images/5.6.jpeg", price:35},
  {name:"Kentang Panggang", level:35, category:"Panggangan BBQ", img:"images/5.7.jpeg", price:35},
  {name:"Fish and Chips", level:41, category:"Panggangan BBQ", img:"images/5.8.jpeg", price:35},
  {name:"Tusuk Lobster", level:48, category:"Panggangan BBQ", img:"images/5.9.jpeg", price:35},
  {name:"Roti Bawang Putih", level:60, category:"Panggangan BBQ", img:"images/5.10.jpeg", price:35},
  {name:"Asparagus Bakar", level:67, category:"Panggangan BBQ", img:"images/5.11.jpeg", price:35},
  {name:"Bawang Bakar", level:68, category:"Panggangan BBQ", img:"images/5.12.jpeg", price:35},
  {name:"Sayur Musim dingin", level:72, category:"Panggangan BBQ", img:"images/5.13.jpeg", price:35},
  {name:"Paprika Isi", level:80, category:"Panggangan BBQ", img:"images/5.14.jpeg", price:35},
  {name:"Terong Panggang", level:90, category:"Panggangan BBQ", img:"images/5.15.jpeg", price:35},
  {name:"Panekuk Pisang", level:94, category:"Panggangan BBQ", img:"images/5.16.jpeg", price:35},
  {name:"Sate Ikan", level:96, category:"Panggangan BBQ", img:"images/5.17.jpeg", price:35},

  {name:"Pai Wortel", level:14, category:"Oven Pai", img:"images/6.1.jpeg", price:35},
  {name:"Pai Labu", level:15, category:"Oven Pai", img:"images/6.2.jpeg", price:35},
  {name:"Pai Daging Babi Asap", level:18, category:"Oven Pai", img:"images/6.3.jpeg", price:35},
  {name:"Pai Apel", level:28, category:"Oven Pai", img:"images/6.4.jpeg", price:35}, 
  {name:"Pai Ikan", level:28, category:"Oven Pai", img:"images/6.5.jpeg", price:35},
  {name:"Pai Feta", level:34, category:"Oven Pai", img:"images/6.6.jpeg", price:35},
  {name:"Kaserol", level:36, category:"Oven Pai", img:"images/6.7.jpeg", price:35},
  {name:"Pai Gembala", level:39, category:"Oven Pai", img:"images/6.8.jpeg", price:35},
  {name:"Pai Asparagus", level:49, category:"Oven Pai", img:"images/6.9.jpeg", price:35},
  {name:"Pai Cokelat", level:65, category:"Oven Pai", img:"images/6.10.jpeg", price:35},
  {name:"Pai Lemon", level:67, category:"Oven Pai", img:"images/6.11.jpeg", price:35},
  {name:"Tar Persik", level:76, category:"Oven Pai", img:"images/6.12.jpeg", price:35},
  {name:"Pai Markisa", level:92, category:"Oven Pai", img:"images/6.13.jpeg", price:35},
  {name:"Pai Jamur", level:97, category:"Oven Pai", img:"images/6.14.jpeg", price:35},
  {name:"Parmesan Terong", level:99, category:"Oven Pai", img:"images/6.15.jpeg", price:35},

  {name:"Sweter", level:17, category:"Mesin Tenun", img:"images/7.1.jpeg", price:35},
  {name:"Kain Katun", level:18, category:"Mesin Tenun", img:"images/7.2.jpeg", price:20},
  {name:"Kupluk Biru", level:19, category:"Mesin Tenun", img:"images/7.3.jpeg", price:35},
  {name:"Sweter Biru", level:20, category:"Mesin Tenun", img:"images/7.4.jpeg", price:35},
  {name:"Syal Merah", level:48, category:"Mesin Tenun", img:"images/7.5.jpeg", price:35},
  {name:"Syal Bunga", level:71, category:"Mesin Tenun", img:"images/7.6.jpeg", price:35},

  {name:"Kemeja Katun", level:19, category:"Mesin Jahit", img:"images/8.1.jpeg", price:35},
  {name:"Celana Berumbai Wol", level:21, category:"Mesin Jahit", img:"images/8.2.jpeg", price:35},
  {name:"Gaun Ungu", level:25, category:"Mesin Jahit", img:"images/8.3.jpeg", price:35},
  {name:"Bantal Nyaman", level:45, category:"Mesin Jahit", img:"images/8.4.jpeg", price:35},
  {name:"Bantal", level:51, category:"Mesin Jahit", img:"images/8.5.jpeg", price:35},
  {name:"Selimut", level:59, category:"Mesin Jahit", img:"images/8.6.jpeg", price:35},

  {name:"Kue Wortel", level:21, category:"Oven Kue", img:"images/9.1.jpeg", price:35},
  {name:"Kue Tar", level:23, category:"Oven Kue", img:"images/9.2.jpeg", price:35},
  {name:"Kue Beri Merah", level:23, category:"Oven Kue", img:"images/9.3.jpeg", price:35},
  {name:"Kue Cheesecake", level:24, category:"Oven Kue", img:"images/9.4.jpeg", price:35},
  {name:"Cheesecake Blueberi", level:31, category:"Oven Kue", img:"images/9.5.jpeg", price:35},
  {name:"Kue Stroberi", level:35, category:"Oven Kue", img:"images/9.6.jpeg", price:35},
  {name:"Kue Cokelat", level:36, category:"Oven Kue", img:"images/9.7.jpeg", price:35},
  {name:"Kue Feta Kentang", level:38, category:"Oven Kue", img:"images/9.8.jpeg", price:35},
  {name:"Kue Apel Madu", level:42, category:"Oven Kue", img:"images/9.9.jpeg", price:35},
  {name:"Kue Mewah", level:54, category:"Oven Kue", img:"images/9.10.jpeg", price:35},
  {name:"Kue Nanas", level:65, category:"Oven Kue", img:"images/9.11.jpeg", price:35},
  {name:"Kue Lemon", level:68, category:"Oven Kue", img:"images/9.12.jpeg", price:35},
  {name:"Kue Buah", level:89, category:"Oven Kue", img:"images/9.13.jpeg", price:35},
  {name:"Bolu Gulung Cokelat", level:95, category:"Oven Kue", img:"images/9.14.jpeg", price:35},
  {name:"Kue Delima", level:108, category:"Oven Kue", img:"images/9.15.jpeg", price:35},

  {name:"Perak Batangan", level:24, category:"Peleburan", img:"images/10.1.jpeg", price:30},
  {name:"Emas Batangan", level:25, category:"Peleburan", img:"images/10.2.jpeg", price:30},
  {name:"Platinum Batangan", level:25, category:"Peleburan", img:"images/10.3.jpeg", price:30},
  {name:"Batu Bara Olahan", level:33, category:"Peleburan", img:"images/10.4.jpeg", price:30},
  {name:"Besi Batangan", level:34, category:"Peleburan", img:"images/10.5.jpeg", price:30},

  {name:"Jus Wortel", level:26, category:"Pemeras Jus", img:"images/11.1.jpeg", price:35},
  {name:"Jus Apel", level:28, category:"Pemeras Jus", img:"images/11.2.jpeg", price:35},
  {name:"Jus Ceri", level:30, category:"Pemeras Jus", img:"images/11.3.jpeg", price:35},
  {name:"Jus Tomat", level:31, category:"Pemeras Jus", img:"images/11.4.jpeg", price:35},
  {name:"Jus Beri", level:31, category:"Pemeras Jus", img:"images/11.5.jpeg", price:35},
  {name:"Jus Nanas", level:52, category:"Pemeras Jus", img:"images/11.6.jpeg", price:35},
  {name:"Jus Jeruk", level:71, category:"Pemeras Jus", img:"images/11.7.jpeg", price:35},
  {name:"Jus Anggur", level:84, category:"Pemeras Jus", img:"images/11.8.jpeg", price:35},
  {name:"Jus Markisa", level:88, category:"Pemeras Jus", img:"images/11.9.jpeg", price:35},
  {name:"Jus Semangka", level:92, category:"Pemeras Jus", img:"images/11.10.jpeg", price:35},
  {name:"Jus Mangga", level:97, category:"Pemeras Jus", img:"images/11.11.jpeg", price:35},
  {name:"Jus Jambu", level:104, category:"Pemeras Jus", img:"images/11.12.jpeg", price:35},

  {name:"Es Krim Vanila", level:29, category:"Mesin Es Krim", img:"images/12.1.jpeg", price:35},
  {name:"Loli Ceri", level:33, category:"Mesin Es Krim", img:"images/12.2.jpeg", price:35},
  {name:"Es Krim Stroberi", level:34, category:"Mesin Es Krim", img:"images/12.3.jpeg", price:35},
  {name:"Es Krim Cokelat", level:39, category:"Mesin Es Krim", img:"images/12.4.jpeg", price:35},
  {name:"Es Krim Wijen", level:50, category:"Mesin Es Krim", img:"images/12.5.jpeg", price:35},
  {name:"Susu Kocok Selai Kacang", level:68, category:"Mesin Es Krim", img:"images/12.6.jpeg", price:35},
  {name:"Sorbet Jeruk", level:78, category:"Mesin Es Krim", img:"images/12.7.jpeg", price:35},
  {name:"Affogato", level:78, category:"Mesin Es Krim", img:"images/12.8.jpeg", price:35},
  {name:"Es Krim Persik", level:83, category:"Mesin Es Krim", img:"images/12.9.jpeg", price:35},
  {name:"Es Krim Mint", level:85, category:"Mesin Es Krim", img:"images/12.10.jpeg", price:35},
  {name:"Banana Split", level:96, category:"Mesin Es Krim", img:"images/12.11.jpeg", price:35},
  {name:"Es Krim Kelapa", level:102, category:"Mesin Es Krim", img:"images/12.12.jpeg", price:35},
  {name:"Sorbet Buah", level:106, category:"Mesin Es Krim", img:"images/12.13.jpeg", price:35},

  {name:"Doner Domba Muda Gulung", level:32, category:"Stan Doner Kebab", img:"images/13.1.jpeg", price:35},
  {name:"Doner Kacang Pedas", level:32, category:"Stan Doner Kebab", img:"images/13.2.jpeg", price:35},
  {name:"Menara Doner Super", level:58, category:"Stan Doner Kebab", img:"images/13.3.jpeg", price:35},

  {name:"Selai Apel", level:35, category:"Pembuat Selai", img:"images/14.1.jpeg", price:35},
  {name:"Selai Rasberi", level:36, category:"Pembuat Selai", img:"images/14.2.jpeg", price:35},
  {name:"Selai Beri Hitam", level:37, category:"Pembuat Selai", img:"images/14.3.jpeg", price:35},
  {name:"Selai Ceri", level:38, catego2ry:"Pembuat Selai", img:"images/14.4.jpeg", price:35},
  {name:"Selai Stroberi", level:50, category:"Pembuat Selai", img:"images/14.5.jpeg", price:35},
  {name:"Selai Bluberi", level:70, category:"Pembuat Selai", img:"images/14.6.jpeg", price:35},
  {name:"Marmalade", level:74, category:"Pembuat Selai", img:"images/14.7.jpeg", price:35},
  {name:"Selai Persik", level:79, category:"Pembuat Selai", img:"images/14.8.jpeg", price:35},
  {name:"Selai Anggur", level:85, category:"Pembuat Selai", img:"images/14.9.jpeg", price:35},
  {name:"Selai Plum", level:94, category:"Pembuat Selai", img:"images/14.10.jpeg", price:35},
  {name:"Selai Markisa", level:96, category:"Pembuat Selai", img:"images/14.11.jpeg", price:35},

  {name:"Gelang", level:38, category:"Pembuat Perhiasan", img:"images/15.1.jpeg", price:35},
  {name:"Kalung", level:39, category:"Pembuat Perhiasan", img:"images/15.2.jpeg", price:35},
  {name:"Cincin Berlian", level:40, category:"Pembuat Perhiasan", img:"images/15.3.jpeg", price:35},
  {name:"Gelang Besi", level:41, category:"Pembuat Perhiasan", img:"images/15.4.jpeg", price:35},
  {name:"Liotin Bunga", level:98, category:"Pembuat Perhiasan", img:"images/15.5.jpeg", price:35},

  {name:"Madu", level:39, category:"Pengekstrak Madu", img:"images/16.2.jpeg", price:30},
  {name:"Lilin Lebah", level:48, category:"Pengekstrak Madu", img:"images/16.3.jpeg", price:30},

  {name:"Espresso", level:42, category:"Kedai Kopi", img:"images/17.1.jpeg", price:35},
  {name:"Kopi Susu", level:43, category:"Kedai Kopi", img:"images/17.2.jpeg", price:35},
  {name:"Kopi Moka", level:45, category:"Kedai Kopi", img:"images/17.3.jpeg", price:35},
  {name:"Moka Rasberi", level:46, category:"Kedai Kopi", img:"images/17.4.jpeg", price:35},
  {name:"Cokelat Panas", level:47, category:"Kedai Kopi", img:"images/17.5.jpeg", price:35},
  {name:"Latte Karamel", level:62, category:"Kedai Kopi", img:"images/17.6.jpeg", price:35},
  {name:"Es Pisang Latte", level:88, category:"Kedai Kopi", img:"images/17.7.jpeg", price:35},

  {name:"Sup Lobster", level:46, category:"Dapur Sup", img:"images/18.1.jpeg", price:35},
  {name:"Sup Domba Muda", level:46, category:"Dapur Sup", img:"images/18.2.jpeg", price:35},
  {name:"Sup Tomat", level:47, category:"Dapur Sup", img:"images/18.3.jpeg", price:35},
  {name:"Sup Labu", level:49, category:"Dapur Sup", img:"images/18.4.jpeg", price:35},
  {name:"Sup Asparagus", level:51, category:"Dapur Sup", img:"images/18.5.jpeg", price:35},
  {name:"Sup Ikan", level:53, category:"Dapur Sup", img:"images/18.6.jpeg", price:35},
  {name:"Sup Kol", level:65, category:"Dapur Sup", img:"images/18.7.jpeg", price:35},
  {name:"Sup Bawang", level:72, category:"Dapur Sup", img:"images/18.8.jpeg", price:35},
  {name:"Mi Kuah", level:73, category:"Dapur Sup", img:"images/18.9.jpeg", price:35},
  {name:"Sup Kentang", level:78, category:"Dapur Sup", img:"images/18.10.jpeg", price:35},
  {name:"Sup Paprika", level:81, category:"Dapur Sup", img:"images/18.11.jpeg", price:35},
  {name:"Sup Brokoli", level:87, category:"Dapur Sup", img:"images/18.12.jpeg", price:35},
  {name:"Sup Jamur", level:104, category:"Dapur Sup", img:"images/18.13.jpeg", price:35},

  {name:"Lilin Stroberi", level:48, category:"Pembuat Lilin", img:"images/19.1.jpeg", price:35},
  {name:"Lilin Rasberi", level:52, category:"Pembuat Lilin", img:"images/19.2.jpeg", price:35},
  {name:"Lilin lemon", level:72, category:"Pembuat Lilin", img:"images/19.3.jpeg", price:35},
  {name:"Lilin Warna Warni", level:84, category:"Pembuat Lilin", img:"images/19.4.jpeg", price:35},
  {name:"Lilin Bunga", level:95, category:"Pembuat Lilin", img:"images/19.5.jpeg", price:35},

  {name:"Buket Pedesaan", level:49, category:"Toko Bunga", img:"images/20.1.jpeg", price:35},
  {name:"Buket Cerah", level:65, category:"Toko Bunga", img:"images/20.2.jpeg", price:35},
  {name:"Buket Glamor", level:73, category:"Toko Bunga", img:"images/20.3.jpeg", price:35},
  {name:"Buket Permen", level:90, category:"Toko Bunga", img:"images/20.4.jpeg", price:35},
  {name:"Buket Ultah", level:92, category:"Toko Bunga", img:"images/20.5.jpeg", price:35},
  {name:"Buket Lembut", level:93, category:"Toko Bunga", img:"images/20.6.jpeg", price:35},
  {name:"Buket Sayuran", level:106, category:"Toko Bunga", img:"images/20.7.jpeg", price:35},

  {name:"Apel Karamel", level:51, category:"Mesin Permen", img:"images/21.1.jpeg", price:35},
  {name:"Permen Toffee", level:52, category:"Mesin Permen", img:"images/21.2.jpeg", price:35},
  {name:"Cokelat", level:54, category:"Mesin Permen", img:"images/21.3.jpeg", price:35},
  {name:"lolipop", level:57, category:"Mesin Permen", img:"images/21.4.jpeg", price:35},
  {name:"Permen Kacang Jeli", level:60, category:"Mesin Permen", img:"images/21.5.jpeg", price:35},
  {name:"Kacang Madu", level:63, category:"Mesin Permen", img:"images/21.6.jpeg", price:35},
  {name:"Permen Kapas", level:75, category:"Mesin Permen", img:"images/21.7.jpeg", price:35},
  {name:"Ampyang Wijen", level:78, category:"Mesin Permen", img:"images/21.8.jpeg", price:35},
  
  {name:"Kecap Asin", level:54, category:"Pembuat Saus", img:"images/22.1.jpeg", price:40},
  {name:"Saus Kacang", level:54, category:"Pembuat Saus", img:"images/22.2.jpeg", price:40},
  {name:"Minyak Zaitun", level:60, category:"Pembuat Saus", img:"images/22.3.jpeg", price:40},
  {name:"Mayones", level:62, category:"Pembuat Saus", img:"images/22.4.jpeg", price:40},
  {name:"Saus Zaitun", level:66, category:"Pembuat Saus", img:"images/22.5.jpeg", price:40},
  {name:"Dadih Lemon", level:66, category:"Pembuat Saus", img:"images/22.6.jpeg", price:40},
  {name:"Saus Tomat", level:69, category:"Pembuat Saus", img:"images/22.7.jpeg", price:40},
  {name:"Salsa", level:77, category:"Pembuat Saus", img:"images/22.8.jpeg", price:40},
  {name:"Hummus", level:95, category:"Pembuat Saus", img:"images/22.9.jpeg", price:40},
  {name:"Saus Markisa", level:100, category:"Pembuat Saus", img:"images/22.10.jpeg", price:40},

  {name:"Sushi Gulung", level:56, category:"Gerai Sushi", img:"images/23.1.jpeg", price:35},
  {name:"Sushi Lobster", level:59, category:"Gerai Sushi", img:"images/23.2.jpeg", price:35},
  {name:"Sushi Telur", level:63, category:"Gerai Sushi", img:"images/23.3.jpeg", price:35},
  {name:"Sushi Gulung Besar", level:76, category:"Gerai Sushi", img:"images/23.4.jpeg", price:35},
  {name:"Nasi Kepal", level:110, category:"Gerai Sushi", img:"images/23.5.jpeg", price:35},

  {name:"Salad Feta", level:58, category:"Gerai Salad", img:"images/24.1.jpeg", price:35},
  {name:"Salad Kacang", level:58, category:"Gerai Salad", img:"images/24.2.jpeg", price:35},
  {name:"Salad BLT", level:62, category:"Gerai Salad", img:"images/24.3.jpeg", price:35},
  {name:"Salad Hidang Laut", level:64, category:"Gerai Salad", img:"images/24.4.jpeg", price:35},
  {name:"Salad Pasta", level:67, category:"Gerai Salad", img:"images/24.5.jpeg", price:35},
  {name:"Lalapan", level:74, category:"Gerai Salad", img:"images/24.6.jpeg", price:35},
  {name:"Salad Kol", level:75, category:"Gerai Salad", img:"images/24.7.jpeg", price:35},
  {name:"Salad Bit Merah", level:76, category:"Gerai Salad", img:"images/24.8.jpeg", price:35},
  {name:"Lumpia", level:78, category:"Gerai Salad", img:"images/24.9.jpeg", price:35},
  {name:"Salad Buah", level:82, category:"Gerai Salad", img:"images/24.10.jpeg", price:35},
  {name:"Salad Musim Panas", level:84, category:"Gerai Salad", img:"images/24.11.jpeg", price:35},
  {name:"Salad Jamur", level:89, category:"Gerai Salad", img:"images/24.12.jpeg", price:35},
  {name:"Salad Jeruk", level:117, category:"Gerai Salad", img:"images/24.13.jpeg", price:35},

  {name:"Roti Bagel Sayuran", level:61, category:"Gerai Roti Lapis", img:"images/25.1.jpeg", price:35},
  {name:"Roti Panggang Daging Asap Babi Asap", level:65, category:"Gerai Roti Lapis", img:"images/25.2.jpeg", price:35},
  {name:"Roti Lapis Telur", level:66, category:"Gerai Roti Lapis", img:"images/25.3.jpeg", price:35},
  {name:"Roti Panggang Madu", level:69, category:"Gerai Roti Lapis", img:"images/25.4.jpeg", price:35},
  {name:"Roti Selai", level:71, category:"Gerai Roti Lapis", img:"images/25.5.jpeg", price:35},
  {name:"Roti Lapis Mentimun", level:79, category:"Gerai Roti Lapis", img:"images/25.6.jpeg", price:35},
  {name:"Bawang Bombai keju", level:84, category:"Gerai Roti Lapis", img:"images/25.7.jpeg", price:35},
  {name:"Roti Panggang Keju Kambing", level:92, category:"Gerai Roti Lapis", img:"images/25.8.jpeg", price:35},
  {name:"Sandwich Gulung Hummus", level:109, category:"Gerai Roti Lapis", img:"images/25.9.jpeg", price:35},

  {name:"Smothie Beri", level:64, category:"Pembuat Smothie", img:"images/26.1.jpeg", price:35},
  {name:"Smothie Sayuran", level:66, category:"Pembuat Smothie", img:"images/26.2.jpeg", price:35},
  {name:"Smothie Yoghurt", level:70, category:"Pembuat Smothie", img:"images/26.3.jpeg", price:35},
  {name:"Smoothie Mentimun", level:70, category:"Pembuat Smothie", img:"images/26.4.jpeg", price:35},
  {name:"Smothie Campur", level:88, category:"Pembuat Smothie", img:"images/26.5.jpeg", price:35},
  {name:"Smoothie Wijen Hitam", level:93, category:"Pembuat Smothie", img:"images/26.6.jpeg", price:35},
  {name:"Smoothie Kakao", level:100, category:"Pembuat Smothie", img:"images/26.7.jpeg", price:35},
  {name:"Smoothie Plum", level:102, category:"Pembuat Smothie", img:"images/26.8.jpeg", price:35},
  {name:"Smoothie Tropis", level:104, category:"Pembuat Smothie", img:"images/26.9.jpeg", price:35},

  {name:"Pasta Segar", level:67, category:"Pembuat Pasta", img:"images/27.1.jpeg", price:25},
  {name:"Mi Beras", level:73, category:"Pembuat Pasta", img:"images/27.2.jpeg", price:25},

  {name:"Minyak Asiri Lemon", level:68, category:"Lab Minyak Asiri", img:"images/28.1.jpeg", price:35},
  {name:"Minyak Asiri Kamomil", level:74, category:"Lab Minyak Asiri", img:"images/28.2.jpeg", price:35},
  {name:"Minyak Asiri Jahe", level:80, category:"Lab Minyak Asiri", img:"images/28.3.jpeg", price:35},
  {name:"Minyak Asiri Mint", level:85, category:"Lab Minyak Asiri", img:"images/28.4.jpeg", price:35},

  {name:"Nasi Goreng", level:69, category:"Dapur Wajan", img:"images/29.1.jpeg", price:35},
  {name:"Oseng Domba Muda", level:69, category:"Dapur Wajan", img:"images/29.2.jpeg", price:35},
  {name:"Ikan Pedas", level:79, category:"Dapur Wajan", img:"images/29.3.jpeg", price:35},
  {name:"Mi Kacang", level:86, category:"Dapur Wajan", img:"images/29.4.jpeg", price:35},
  {name:"Tumis Tahu", level:89, category:"Dapur Wajan", img:"images/29.5.jpeg", price:35},

  {name:"Topi Cloche", level:70, category:"Pembuat Topi", img:"images/30.1.jpeg", price:35},
  {name:"Topi Tinggi", level:72, category:"Pembuat Topi", img:"images/30.2.jpeg", price:35},
  {name:"Topi Matahari", level:74, category:"Pembuat Topi", img:"images/30.3.jpeg", price:35},
  {name:"Tiara Bunga", level:86, category:"Pembuat Topi", img:"images/30.4.jpeg", price:35},

  {name:"Gnocchi", level:72, category:"Dapur Pasta", img:"images/31.1.jpeg", price:35},
  {name:"Lasagna Sayur", level:74, category:"Dapur Pasta", img:"images/31.2.jpeg", price:35},
  {name:"Pasta Lobster", level:79, category:"Dapur Pasta", img:"images/31.3.jpeg", price:35},
  {name:"Pasta Carbonara", level:83, category:"Dapur Pasta", img:"images/31.4.jpeg", price:35},
  {name:"Pasta Brokoli", level:83, category:"Dapur Pasta", img:"images/31.5.jpeg", price:35},
  {name:"Pasta Pedas", level:87, category:"Dapur Pasta", img:"images/31.6.jpeg", price:35},
  {name:"Pasta Jamur", level:101, category:"Dapur Pasta", img:"images/31.7.jpeg", price:35},

  {name:"Hot Dog", level:75, category:"Stan Hot Dog", img:"images/32.1.jpeg", price:35},
  {name:"Hot Dog Tahu", level:76, category:"Stan Hot Dog", img:"images/32.2.jpeg", price:35},
  {name:"Hot Dog Jagung", level:78, category:"Stan Hot Dog", img:"images/32.3.jpeg", price:35},
  {name:"Sosis Bawang", level:80, category:"Stan Hot Dog", img:"images/32.4.jpeg", price:35},

  {name:"Donat Klasik", level:76, category:"Pembuat Donat", img:"images/33.1.jpeg", price:35},
  {name:"Donat Meses", level:79, category:"Pembuat Donat", img:"images/33.2.jpeg", price:35},
  {name:"Donat Kacang", level:82, category:"Pembuat Donat", img:"images/33.3.jpeg", price:35},
  {name:"Donat Krim", level:86, category:"Pembuat Donat", img:"images/33.4.jpeg", price:35},
  {name:"Donat Daging Babi Asap", level:88, category:"Pembuat Donat", img:"images/33.5.jpeg", price:35},
  {name:"Donat Selai", level:93, category:"Pembuat Donat", img:"images/33.6.jpeg", price:35},
  
  {name:"Taco", level:77, category:"Dapur Taco", img:"images/34.1.jpeg", price:35},
  {name:"Taco Kacang Pedas", level:77, category:"Dapur Taco", img:"images/34.2.jpeg", price:35},
  {name:"Taco Ikan", level:79, category:"Dapur Taco", img:"images/34.3.jpeg", price:35},
  {name:"Quesadilla", level:82, category:"Dapur Taco", img:"images/34.4.jpeg", price:35},
  {name:"Nachos", level:87, category:"Dapur Taco", img:"images/34.5.jpeg", price:35},

  {name:"Omelet Warna warni", level:77, category:"Dapur Omelet", img:"images/35.1.jpeg", price:35},
  {name:"Omelet Sayur", level:77, category:"Dapur Omelet", img:"images/35.2.jpeg", price:35},
  {name:"Omelet Keju", level:79, category:"Dapur Omelet", img:"images/35.3.jpeg", price:35},
  {name:"Omelet Nasi", level:83, category:"Dapur Omelet", img:"images/35.4.jpeg", price:35},
  {name:"Omelet Kentang", level:87, category:"Dapur Omelet", img:"images/35.5.jpeg", price:35},

  {name:"Teh Hijau", level:80, category:"Gerai Teh", img:"images/36.1.jpeg", price:35},
  {name:"Teh Susu", level:81, category:"Gerai Teh", img:"images/36.2.jpeg", price:35},
  {name:"Teh Madu", level:83, category:"Gerai Teh", img:"images/36.3.jpeg", price:35},
  {name:"Teh Lemom", level:86, category:"Gerai Teh", img:"images/36.4.jpeg", price:35},
  {name:"Teh Jahe Apel", level:88, category:"Gerai Teh", img:"images/36.5.jpeg", price:35},
  {name:"Teh Jeruk", level:89, category:"Gerai Teh", img:"images/36.6.jpeg", price:35},
  {name:"Es teh", level:92, category:"Gerai Teh", img:"images/36.7.jpeg", price:35},
  {name:"Teh Mint", level:97, category:"Gerai Teh", img:"images/36.8.jpeg", price:35},
  {name:"Teh Kamomil", level:100, category:"Gerai Teh", img:"images/36.9.jpeg", price:35},
  {name:"Teh Delima", level:107, category:"Gerai Teh", img:"images/36.10.jpeg", price:35},

  {name:"Fondu Cokelat", level:81, category:"Panci Fondu", img:"images/37.1.jpeg", price:35},
  {name:"Fondu Daging Babi Asap", level:86, category:"Panci Fondu", img:"images/37.2.jpeg", price:35},
  {name:"Fondu Keju", level:91, category:"Panci Fondu", img:"images/37.3.jpeg", price:35},
  {name:"Fondu Tropis", level:100, category:"Panci Fondu", img:"images/37.4.jpeg", price:35},

  {name:"Sabun Madu", level:84, category:"Toko Kecantikan", img:"images/38.1.jpeg", price:35},
  {name:"Lasion Lemon", level:84, category:"Toko Kecantikan", img:"images/38.2.jpeg", price:35},
  {name:"Sabun Lulur", level:93, category:"Toko Kecantikan", img:"images/38.3.jpeg", price:35},
  {name:"Masker Wajah Madu", level:99, category:"Toko Kecantikan", img:"images/38.4.jpeg", price:35},
  {name:"Sabun Mewah", level:121, category:"Toko Kecantikan", img:"images/38.5.jpeg", price:35},

  {name:"Daging Babi Asap Goreng", level:87, category:"Penggorengan", img:"images/39.1.jpeg", price:35},
  {name:"Pastel", level:91, category:"Penggorengan", img:"images/39.1.jpeg", price:35},
  {name:"Cabai Goreng Tepung", level:98, category:"Penggorengan", img:"images/39.1.jpeg", price:35},
  {name:"Falafel", level:98, category:"Penggorengan", img:"images/39.1.jpeg", price:35},
  {name:"Permen Goreng", level:100, category:"Penggorengan", img:"images/39.1.jpeg", price:35},
  {name:"Samosa", level:103, category:"Penggorengan", img:"images/39.1.jpeg", price:35},

  {name:"Acar", level:91, category:"Mesin Pengawetan", img:"images/40.1.jpeg", price:35},
  {name:"Ikan Kaleng", level:95, category:"Mesin Pengawetan", img:"images/40.2.jpeg", price:35},
  {name:"Kimci", level:98, category:"Mesin Pengawetan", img:"images/40.3.jpeg", price:35},
  {name:"Buah Kering", level:102, category:"Mesin Pengawetan", img:"images/40.4.jpeg", price:35},
  {name:"Manisan Jambu", level:104, category:"Mesin Pengawetan", img:"images/40.5.jpeg", price:35},

  {name:"Teko Teh", level:94, category:"Studio Gerabah", img:"images/41.1.jpeg", price:35},
  {name:"Pot Tanaman", level:96, category:"Studio Gerabah", img:"images/41.2.jpeg", price:35},
  {name:"Cangkir Keramik", level:99, category:"Studio Gerabah", img:"images/41.3.jpeg", price:35},

  {name:"Fudge Kaya Rasa", level:99, category:"Kedai Fudge", img:"images/42.1.jpeg", price:35},
  {name:"Fudge Mint", level:102, category:"Kedai Fudge", img:"images/42.2.jpeg", price:35},
  {name:"Fudge Cabai", level:104, category:"Kedai Fudge", img:"images/42.3.jpeg", price:35},
  {name:"Fudge Lemon", level:108, category:"Kedai Fudge", img:"images/42.4.jpeg", price:35},
  {name:"Fudge Kacang", level:111, category:"Kedai Fudge", img:"images/42.5.jpeg", price:35},

  {name:"Yoghurt", level:103, category:"Pembuat Yoghurt", img:"images/43.1.jpeg", price:35},
  {name:"Yoghurt Stroberi", level:105, category:"Pembuat Yoghurt", img:"images/43.2.jpeg", price:35},
  {name:"Yoghurt Tropis", level:109, category:"Pembuat Yoghurt", img:"images/43.3.jpeg", price:35},
  {name:"Yoghurt Pagi", level:119, category:"Pembuat Yoghurt", img:"images/43.4.jpeg", price:35},

  {name:"Sup Kacang Arab", level:106, category:"Dapur Kuali", img:"images/44.1.jpeg", price:35},
  {name:"Sup Cabai", level:109, category:"Dapur Kuali", img:"images/44.2.jpeg", price:35},
  {name:"Sup Musim Dingin", level:112, category:"Dapur Kuali", img:"images/44.3.jpeg", price:35},

  {name:"Cupcake Polos", level:109, category:"Pembuat Cupcake", img:"images/45.1.jpeg", price:35},
  {name:"Cupcake Jambu", level:109, category:"Pembuat Cupcake", img:"images/45.2.jpeg", price:35},
  {name:"Cupcake Tropis", level:112, category:"Pembuat Cupcake", img:"images/45.3.jpeg", price:35},
  {name:"Cupcake Kukis", level:114, category:"Pembuat Cupcake", img:"images/45.4.jpeg", price:35},

  {name:"Diffuser Wangi", level:110, category:"Toko Parfum", img:"images/46.1.jpeg", price:35},
  {name:"Parfum Segar", level:113, category:"Toko Parfum", img:"images/46.2.jpeg", price:35},
  {name:"Diffuser Relaksasi", level:116, category:"Toko Parfum", img:"images/46.3.jpeg", price:35},

  {name:"Wafel Polos", level:114, category:"Pembuat Wafel", img:"images/47.1.jpeg", price:35},
  {name:"Wafel Beri", level:114, category:"Pembuat Wafel", img:"images/47.2.jpeg", price:35},
  {name:"Wafel Cokelat", level:117, category:"Pembuat Wafel", img:"images/47.3.jpeg", price:35},
  {name:"Wafel Bluberi Cokelat Putih", level:118, category:"Pembuat Wafel", img:"images/47.4.jpeg", price:35},
  {name:"Wafel Pagi", level:119, category:"Pembuat Wafel", img:"images/47.5.jpeg", price:35},

  {name:"Bubur Apel", level:119, category:"Kedai Bubur", img:"images/48.1.jpeg", price:35},
  {name:"Bubur Manis", level:120, category:"Kedai Bubur", img:"images/48.2.jpeg", price:35},
  {name:"Bubur Segar", level:122, category:"Kedai Bubur", img:"images/48.3.jpeg", price:35},

  {name:"Susu Kocok Vanila", level:124, category:"Stan Susu Kocok", img:"images/49.1.jpeg", price:35},
  {name:"Susu Kocok Moka", level:125, category:"Stan Susu Kocok", img:"images/49.2.jpeg", price:35},
  {name:"Susu Kocok Buah", level:126, category:"Stan Susu Kocok", img:"images/49.3.jpeg", price:35},

];
ITEMS.forEach((f,i)=> f.id = i);
